config/routes.rb
Helpdesk::Application.routes.draw do
  root to: "tickets#index"

  resources :tickets

  namespace :api do
    resources :tickets, only: [ :create ]
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :answer, :question, :requested_by, :title

  validates :question, :requested_by, :title, presence: true

  def self.update_from_postmark(mitt)
      ticket_id = mitt.to.split("@").first.split("+").last
      ticket = Ticket.find(ticket_id)
      ticket.answer = mitt.text_body
      ticket.save
  end

end

app/controllers/api/tickets_controller.rb
class Api::TicketsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    if Ticket.update_from_postmark(Postmark::Mitt.new(request.body.read))
      render :text => "Created a post!", status: :created
    else
      render :text => "Unauthorized!", status: :unauthorized
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :find_ticket, only: [:show, :edit, :update]

  def index
    @tickets = Ticket.order("created_at DESC")
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.create(params[:ticket])
    if @ticket.valid?
      flash[:notice] = "Ticket successfully created."
      TicketMailer.new_ticket(@ticket).deliver
      redirect_to tickets_path 
    else
      flash[:alert] = "Error creating your ticket."
      render action: :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to @ticket
    else
      flash[:alert] = "Error updating ticket."
      render action: "edit"
    end
  end

  def destroy
    Ticket.find(params[:id]).destroy
    flash[:notice] = "Ticket has been removed."
    redirect_to tickets_path
  end

private
  def find_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/api/tickets_helper.rb
module Api::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helpdesk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= nav_bar  fixed: :top %>
<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for @ticket, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :requested_by, "Email", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :requested_by, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, "Subject", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :question, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :question, :class => 'text_area' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tickets_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/index.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:answer) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= link_to ticket.title, ticket_path(ticket) %></td>
        <td><%= ticket.question %></td>
        <% if ticket.answer.nil? %>
          <td>none yet...</td>
        <% else %>
          <td><%= link_to "view", ticket_path(ticket) %></td>       
        <% end %>
        <td><%=l ticket.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_ticket_path(ticket), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      ticket_path(ticket),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ticket_path,
            :class => 'btn btn-primary' %>

app/views/tickets/new.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tickets/show.html.erb
<%- model_class = Ticket -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @ticket.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question) %>:</strong></dt>
  <dd><%= @ticket.question %></dd>
  <dt><strong><%= model_class.human_attribute_name(:answer) %>:</strong></dt>
  <% if @ticket.answer.nil? %>
    <dd>Ticket is still being processed by our helpdesk staff.  Please check back soon.</dd>
  <% else %>
    <dd><%= @ticket.answer %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:requested_by) %>:</strong></dt>
  <dd><%= @ticket.requested_by %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tickets_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ticket_path(@ticket), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ticket_path(@ticket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>